### PR TITLE
Fixed Slack's redirect URL

### LINKED ISSUE #17: Open external links in default browser
Any external links are opened in a web kit window. We should open these in the default system browser.

### PR DESCRIPTION
**Pull request by twolfson**
Slack has moved from `slack-redir.com` to `slack-redir.net` for all of their redirect URLs. This PR updates our code to match that change. Fixes #17.

In this PR:

- Moved `validSlackRedirect` from `.com` to `.net`

selection_106

/cc @wlaurance

### CODE REVIEW

File: app/js/index.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ window.webslack = (function (gui, urllib, pkg, localStorage) {
 
 	var win = gui.Window.get();
 	var validSlackSubdomain = /(.+)\.slack.com/i;
-	var validSlackRedirect = /(.+\.)?slack-redir.com/i;
+	var validSlackRedirect = /(.+\.)?slack-redir.net/i;
```
Comment (twolfson) [inline app/js/index.js]: @canuc Any reason why we have a URL check for new windows? Why not open all of them as is?
